# Generated by Django 4.2.2 on 2023-07-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
