# Generated by Django 4.2.2 on 2023-07-28 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderIce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ice')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderitem')),
            ],
        ),
    ]
